//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteShares
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int NoteId { get; set; }
        public string NoteSrc { get; set; }
        public int CourseId { get; set; }
        public int UserId { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual User User { get; set; }
    }
}
